version = 0.1

[default.deploy.parameters]
stack_name = "babys-calendar-dev"
region = "af-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=dev"
resolve_s3 = true
